[package]
name = "hostlist"
version = "0.1.0"
authors = ["Janne Blomqvist <blomqvist.janne@gmail.com>"]
edition = "2018"
description = "Hostlist library for Rust"
license = "MIT"

[dependencies]
nom = { version = "^4.1", features = ["verbose-errors"] }
